movento_root/movento_root/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movento_web_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movento_root/movento_web_app/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import SubCategorySitemap, DetailSubCategorySitemap, DetailPostSitemap, StaticViewSitemap

sitemaps = {
    'SubCategorySitemap': SubCategorySitemap,
    'DetailSubCategorySitemap': DetailSubCategorySitemap,
    'DetailPostSitemap': DetailPostSitemap,
    'StaticViewSitemap': StaticViewSitemap,
}

urlpatterns = [
    path("", views.index, name="home"),
    path("thiet-ke-thi-cong/<str:subcatename>", views.subcategory, name="service_subcategory"),
    path("thiet-ke-thi-cong/<str:subcatename>/<str:detailsubcatename>", views.detailsubcategory, name="service_detailsubcategory"),
    path("thiet-ke-thi-cong/<str:subcatename>/<str:detailsubcatename>/<str:detailpostname>", views.detailpost, name="service_detailpost"),
    path("san-pham/<str:cate_code>", views.product_category, name="product_category"),
    path("san-pham/<str:cate_code>/<str:product_code>", views.product_detail, name="product_detail"),
    path("tim-kiem-san-pham", views.search_product, name="search_product"),
    path("tim-kiem-san-pham/<str:tagname>", views.search_product_tagname, name="search_product_tagname"),
    path("lien-he", views.contact, name="contact"),
    path("yeu-cau-tu-van", views.submit_request, name="success"),
    path("ho-so-nang-luc", views.about, name="about"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="")
]

movento_root/movento_web_app/models.py
from django.db import models
from django.urls import reverse
from froala_editor.fields import FroalaField


#
# Category models
#


class SubCategory(models.Model):
    CATE_TYPE = (
        ('0', 'Dịch vụ'),
        ('1', 'Sản phẩm')
    )

    COLUMN_TYPE = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    )
    name = models.CharField(max_length=100, verbose_name="Tên danh mục")
    cate_type = models.CharField(max_length=20, choices=CATE_TYPE, verbose_name="Loại danh mục", default='0')
    description = models.TextField("Mô tả")
    image = models.ImageField(upload_to='category_images', verbose_name="Hình ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")
    is_homepage_content = models.BooleanField("Hiển thị ở mục giới thiệu ?", default=True)
    column_type = models.CharField(max_length=20, choices=COLUMN_TYPE, verbose_name="Số cột hiển thị")
    code = models.SlugField(max_length=100, verbose_name="Mã danh mục")

    class Meta:
        verbose_name = "Danh mục cấp 1"
        verbose_name_plural = "Danh mục cấp 1"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("service_subcategory", args=[self.code, ])


class DetailSubCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên danh mục")
    description = models.TextField("Mô tả")
    image = models.ImageField(upload_to='category_images', verbose_name="Hình ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")
    parent_cate = models.ForeignKey(SubCategory, blank=True, null=True, on_delete=models.CASCADE,
                                    verbose_name="Danh mục cha")
    code = models.SlugField(max_length=100, verbose_name="Mã danh mục")

    class Meta:
        verbose_name = "Danh mục cấp 2"
        verbose_name_plural = "Danh mục cấp 2"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("service_detailsubcategory", args=[self.parent_cate.code, self.code])


#
# Content models
#


class Content(models.Model):
    COMPONENT_TYPE = (
        ('0', 'Cover'),
        ('1', 'Slide ảnh giới thiệu'),
        ('2', 'Dịch vụ cung cấp'),
        ('3', 'Công trình tiêu biểu'),
        ('4', 'Nhận xét khách hàng'),
        ('5', 'Call to action'),
        ('7', 'Giới thiệu chung về công ty'),
        ('8', 'Quá trình thành lập và phát triển'),
        ('9', 'Cơ sở vật chất'),
        ('10', 'Ngành nghề kinh doanh'),
        ('11', 'Các dự án đã thực hiện'),
        ('12', 'Tầm nhìn & sứ mệnh, giá trị cốt lõi'),
        ('13', 'Cơ sở pháp lý'),
        ('14', 'Giới thiệu chung'),
        ('15', 'Năng lực kinh nghiệm'),
        ('16', 'Ban lãnh đạo tổ chức'),
    )

    PAGE_TYPE = (
        ('0', 'Trang chủ'),
        ('1', 'Giới thiệu'),
        ('2', 'Danh mục cấp 2')
    )
    name = models.CharField(max_length=100, verbose_name="Tên nội dung")
    page = models.CharField(max_length=20, choices=PAGE_TYPE, verbose_name="Trang")
    component_type = models.CharField(max_length=20, choices=COMPONENT_TYPE, verbose_name="Bộ phận")
    title = models.CharField(blank=True, null=True, max_length=100, verbose_name="Tiêu đề")
    description = FroalaField(blank=True, null=True, verbose_name="Nội dung")

    class Meta:
        verbose_name = "Nội dung trang"
        verbose_name_plural = "Nội dung trang"

    def __str__(self):
        return self.name


class ContentImages(models.Model):
    image = models.ImageField(upload_to='content_images', verbose_name="Hình ảnh")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh", default="")
    content = models.ForeignKey(Content, blank=True, null=True, on_delete=models.CASCADE,
                                verbose_name="Nội dung")

    class Meta:
        verbose_name = "Hình ảnh nội dung"
        verbose_name_plural = "Hình ảnh nội dung"

    def __str__(self):
        return str(self.id)


#
# Tag models
#

class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên tag", default="")
    code = models.SlugField(max_length=100, verbose_name="Mã tag", default="")

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tag"

    def __str__(self):
        return str(self.name)


#
# Post models
#

class DetailPost(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên bài viết")
    avatar = models.ImageField(upload_to='post_avatar_images', verbose_name="Ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")
    category = models.ForeignKey(DetailSubCategory, blank=True, null=True, on_delete=models.CASCADE,
                                 verbose_name="Danh mục")
    tag = models.ManyToManyField(Tag, verbose_name="Tags")
    customer = models.CharField(max_length=100, verbose_name="Tên khách hàng")
    address = models.CharField(max_length=100, verbose_name="Địa chỉ")
    start_date = models.DateField(verbose_name="Ngày thiết kế")
    code = models.SlugField(max_length=100, verbose_name="Mã bài viết")
    description = models.TextField(blank=True, null=True, verbose_name="Mô tả ngắn")
    main_content = FroalaField(default="")
    is_outstanding = models.BooleanField(default=False, verbose_name="Bài viết nổi bật ?")

    class Meta:
        verbose_name = "Bài viết chi tiết"
        verbose_name_plural = "Bài viết chi tiết"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        detail_subcategory = DetailSubCategory.objects.get(pk=self.category.id)
        subcategory = SubCategory.objects.get(pk=detail_subcategory.parent_cate.id)
        return reverse("service_detailpost", args=[subcategory.code, detail_subcategory.code, self.code])


class DetailPostImages(models.Model):
    image = models.ImageField(upload_to='post_detail_images', verbose_name="Hình ảnh")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh", default="")
    post = models.ForeignKey(DetailPost, blank=True, null=True, on_delete=models.CASCADE,
                             verbose_name="Bài viết")

    class Meta:
        verbose_name = "Hình ảnh bài viết"
        verbose_name_plural = "Hình ảnh bài viết"

    def __str__(self):
        return str(self.id)


#
# Partner models
#

class Partner(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên đối tác")
    web = models.URLField(blank=True, verbose_name="Link web")
    image = models.ImageField(upload_to='partner_images', verbose_name="Hình ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")

    class Meta:
        verbose_name = "Đối tác"
        verbose_name_plural = "Đối tác"

    def __str__(self):
        return str(self.name)


#
# Customer models
#

class CustomerComment(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên khách hàng")
    image = models.ImageField(upload_to='content_images', verbose_name="Hình ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")
    description = models.TextField(blank=True, null=True, verbose_name="Nội dung")

    class Meta:
        verbose_name = "Nhận xét khách hàng"
        verbose_name_plural = "Nhận xét khách hàng"

    def __str__(self):
        return str(self.name)


#
# Contact models
#

class Contact(models.Model):
    company_name = models.CharField(max_length=100, verbose_name="Tên công ty")
    tel = models.CharField(max_length=100, verbose_name="Tel")
    mobile = models.CharField(max_length=100, verbose_name="Mobile")
    email = models.CharField(max_length=100, verbose_name="Email")
    showroom = models.TextField(verbose_name="Showroom & office")
    factory = models.TextField(verbose_name="Xưởng")

    class Meta:
        verbose_name = "Thông tin liên hệ"
        verbose_name_plural = "Thông tin liên hệ"

    def __str__(self):
        return str(self.company_name)


#
# Product models
#

class ProductCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name="Tên danh mục")
    image = models.ImageField(upload_to='product_category_images', verbose_name="Ảnh đại diện", default="")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh", default="")
    description = models.TextField("Mô tả")
    is_homepage_content = models.BooleanField("Hiển thị ở mục giới thiệu ?", default=True)
    code = models.SlugField(max_length=100, verbose_name="Mã danh mục")
    tag = models.ManyToManyField(Tag, verbose_name="Tags")

    class Meta:
        verbose_name = "Danh mục sản phẩm"
        verbose_name_plural = "Danh mục sản phẩm"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("product_category", args=[self.code, ])


class ProductAttrs_Color(models.Model):
    name = models.CharField(max_length=100, verbose_name="Màu sắc", default="")

    class Meta:
        verbose_name = "Màu sắc sản phẩm"
        verbose_name_plural = "Màu sắc sản phẩm"

    def __str__(self):
        return str(self.name)


class ProductAttrs_Material(models.Model):
    name = models.CharField(max_length=100, verbose_name="Vật liệu", default="")

    class Meta:
        verbose_name = "Chất liệu sản phẩm"
        verbose_name_plural = "Chất liệu sản phẩm"

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    RATING = (
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    name = models.CharField(max_length=100, verbose_name="Tên sản phẩm")
    avatar = models.ImageField(upload_to='post_avatar_images', verbose_name="Ảnh đại diện")
    image_alt = models.CharField(max_length=100, verbose_name="Mô tả ảnh đại diện", default="")

movento_root/movento_web_app/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Họ tên',
                'onfocus': "this.placeholder = ''",
                'onblur': "this.placeholder = 'Họ tên'",
                'class': "common-input mb-20 form-control",
            }
        )
    )
    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email',
                'onfocus': "this.placeholder = ''",
                'onblur': "this.placeholder = 'Email'",
                'class': "common-input mb-20 form-control",
                'pattern': "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$",
            }
        )
    )
    phone = forms.CharField(
        max_length=12,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Số điện thoại',
                'onfocus': "this.placeholder = ''",
                'onblur': "this.placeholder = 'Số điện thoại'",
                'class': "common-input mb-20 form-control",
                'pattern': "[0-9]{10}",
            }
        )
    )
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Mô tả yêu cầu',
                'onfocus': "this.placeholder = ''",
                'onblur': "this.placeholder = 'Mô tả yêu cầu'",
                'class': "common-input mb-20 form-control",
            }
        )
    )

movento_root/movento_web_app/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block Title %}
Liên hệ
{% endblock Title %}

{% block MainContent %}
<link rel="stylesheet" href="{% static 'css/custom_css/homepage.css' %}">

<style>
    {% with CoverContent.contentimages_set.all|first as firstItem %}
        .banner-area {
            background: url({{ firstItem.image.url }}) center;
            background-size: cover;
        }
    {% endwith %}
</style>

<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Liên hệ
                </h1>
                <p class="text-white link-nav"><a href="{% url 'home' %}">Trang chủ </a>  <span class="lnr lnr-arrow-right"></span>  <a href=""> Liên hệ </a></p>
            </div>
        </div>
    </div>
</section>

<div class="container pt-50 pb-50">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14896.076594994245!2d105.7529162!3d21.0319198!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x316de782537c21f0!2zTuG7mWkgVGjhuqV0IE1vdmVudG8!5e0!3m2!1svi!2s!4v1544261256578" class="col-lg-12" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
{% endblock MainContent %}

{% block CustomJs %}
<script>
    $(".callto-action-area").hide();
    $(".brands-area").hide();
</script>
{% endblock CustomJs %}

movento_root/movento_web_app/templates/detailpost.html
{% extends "base.html" %}
{% load static %}
{% block Title %}
{{ DetailPost.name }}
{% endblock Title %}

{% block MainContent %}
<link rel="stylesheet" href="{% static 'css/custom_css/detailpost.css' %}">
<link rel="stylesheet" href="{% static 'css/custom_css/lightbox.min.css' %}">
<script type="text/javascript" src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
<style>
    .banner-area {
        background: url({{ DetailSubCategory.image.url }}) center;
        background-size: cover;
    }
</style>
<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    {{ DetailSubCategory.name }}
                </h1>
                <p class="text-white link-nav"><a href="{% url 'home' %}">Trang chủ </a>  <span class="lnr lnr-arrow-right"></span>  <a href="{% url 'service_subcategory' SubCategory.code %}"> {{ SubCategory.name }}</a><span class="lnr lnr-arrow-right"></span>  <a href=""> {{ DetailSubCategory.name }}</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- Start project-details Area -->
<section class="project-details-area section-gap">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 project-details-left">
                <img class="img-fluid" src="{{ DetailPost.avatar.url }}" alt="{{ DetailPost.image_alt }}">
            </div>
            <div class="col-lg-6 project-details-right">
                <h3 class="pb-20">{{ DetailPost.name }}</h3>
                <p>{{ DetailPost.description }}</p>
                <div class="details-info d-flex flex-row">
                    <ul class="names">
                        <li>Tên khách hàng</li>
                        <li>Địa chỉ</li>
                        <li>Ngày thiết kế</li>
                    </ul>
                    <ul class="desc">
                        <li>: {{ DetailPost.customer }}</li>
                        <li>: {{ DetailPost.address }}</li>
                        <li>: {{ DetailPost.start_date }}</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-12 project-desc mt-60">
                {% autoescape off %}
                    <p>{{ DetailPost.main_content }}</p>
                {% endautoescape %}
            </div>
        </div>
    </div>
</section>
<!-- End project-details Area -->

<!-- Photo Grid -->
<div class="row-grid container">
    <div class="column-grid gallery">
        {% for postimage in DetailPost.detailpostimages_set.all %}
            <a href="{{ postimage.image.url }}" data-lightbox="mygallery">
                <img src="{{ postimage.image.url }}" style="width:100%" alt="{{ postimage.image_alt }}">
            </a>
            {% if forloop.counter0 == GridImageColumnCount %}
                </div>
			    <div class="column-grid gallery">
            {% endif %}
        {% endfor %}
    </div>
	<!-- Plug in Like/Share -->
	<div class="fb-like pt-30" style="width:100%;" data-href="" data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
	<!-- Plug in comment -->
	<div class="fb-comments" data-href="" data-numposts="5"></div>
</div>
<!-- End Photo Grid -->

{% endblock MainContent %}

{% block CustomJs %}
<script type="text/javascript">
	$( document ).ready(function() {
		var pageURL = $(location).attr("href");
		$(".fb-like").attr("data-href", pageURL);
		$(".fb-comments").attr("data-href", pageURL);
	});
</script>
{% endblock CustomJs %}

movento_root/movento_web_app/templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% block Title %}
Movento
{% endblock Title %}

{% block MainContent %}
<link rel="stylesheet" href="{% static 'css/custom_css/homepage.css' %}">

<style>
    {% with CoverContent.contentimages_set.all|first as firstItem %}
        .banner-area {
            background: url({{ firstItem.image.url }}) center;
            background-size: cover;
        }
    {% endwith %}
</style>

<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row fullscreen d-flex justify-content-center align-items-center">
            <div class="banner-content col-lg-9 col-md-12 justify-content-center">
                <img class="img-responsive logo2" src="{% static 'img/logo.svg' %}" alt="Movento Logo"/>
                <h1>
                    {{ CoverContent.title }}
                </h1>
                <div class="text-white mx-auto">
                    {% autoescape off %}
                    {{ CoverContent.description }}
                    {% endautoescape %}
                </div>
                <a href="{% url 'about' %}" class="primary-btn header-btn text-uppercase mt-10">Tìm hiểu ngay</a>
            </div>
        </div>
    </div>
</section>

<!-- Image slider Area -->
{% if SliderContent.contentimages_set.count > 0 %}
<section class="image-slider container">
    <div id="HomepageSlider" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for slide in SliderContent.contentimages_set.all %}
                {% if forloop.counter0 == 0 %}
                    <li data-target="#HomepageSlider" data-slide-to="0" class="active">
                {% else %}
                    <li data-target="#HomepageSlider" data-slide-to="{{forloop.counter0}}">
                {% endif %}
            {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            {% for slide in SliderContent.contentimages_set.all %}
                {% if forloop.counter0 == 0 %}
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="{{ slide.image.url }}" alt="{{ slide.image_alt }}">
                    </div>
                {% else %}
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{{ slide.image.url }}" alt="{{ slide.image_alt }}">
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#HomepageSlider" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#HomepageSlider" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
{% endif %}
<!-- End image slider Area -->

<!-- Start service Area -->
<section class="service-area section-gap" id="service">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 pb-10 header-text text-center">
                <h1 class="mb-10">{{ FeatureContent.title }}</h1>
                <p>
                    {{ FeatureContent.description }}
                </p>
            </div>
        </div>
        <div class="row">
            {% for sub_category in DisplayServiceCategory %}
                <div class="col-lg-4">
                    <div class="single-service">
                        {% if sub_category in ServiceMenu %}
                            <a href="{% url 'service_subcategory' sub_category.code %}"><h4>{{ sub_category.name }}</h4></a>
                        {% else %}
                            <a href="{% url 'product_subcategory' sub_category.code %}"><h4>{{ sub_category.name }}</h4></a>
                        {% endif %}
                        <p>{{ sub_category.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- End service Area -->

<!-- Start gallery Area -->
<section class="gallery-area pb-120">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 pb-10 header-text text-center">
                <h1 class="pb-10">{{ ProductContent.title }}</h1>
            </div>
        </div>
        {% for sub_category in DisplayServiceCategory %}
        <div class="wrapper-center">
            {% if sub_category in ServiceMenu %}
                <a class="primary-btn text-uppercase gallery-btn" href="{% url 'service_subcategory' sub_category.code %}">{{ sub_category.name }}</a>
            {% else %}
                <a class="primary-btn text-uppercase gallery-btn" href="{% url 'product_subcategory' sub_category.code %}">{{ sub_category.name }}</a>
            {% endif %}
        </div>
        <div class="row grid-row" col-count="{{ sub_category.column_type }}">
            {% for detail_category in sub_category.detailsubcategory_set.all %}
                {% for post in detail_category.detailpost_set.all %}
                    {% if post.is_outstanding %}
                        {% if sub_category.column_type == '1'%}
                            <div class="col-lg-12 grid-item">
                        {% elif sub_category.column_type == '2' %}
                            <div class="col-lg-6 grid-item">
                        {% elif sub_category.column_type == '3' %}
                            <div class="col-lg-4 grid-item">
                        {% elif sub_category.column_type == '4' %}
                            <div class="col-lg-3 grid-item">
                        {% endif %}
                                <div class="single-gallery">
                                    <div class="content">
                                        {% if sub_category in ServiceMenu %}
                                        <a href="{% url 'service_detailpost' sub_category.code detail_category.code post.code %}">
                                        {% else %}
                                        <a href="{% url 'product_detailpost' sub_category.code detail_category.code post.code %}">
                                        {% endif %}
                                            <div class="content-overlay"></div>
                                            <img class="content-image img-fluid d-block mx-auto"
                                                 src="{{ post.avatar.url }}"
                                                 alt="{{ post.image_alt }}">
                                            <div class="content-details fadeIn-bottom">
                                                <h3 class="content-title mx-auto">{{ post.name }}</h3>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <div class="wrapper-right">
                <button class="primary-btn header-btn text-uppercase more-detail">Xem thêm</button>
            </div>
        </div>
        {% endfor %}
    </div>
    <!--End Container DIV-->
</section>
<!-- End gallery Area -->

<!-- Start testimonial Area -->
<section class="testimonial-area pt-120">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">{{ CommentTitle.title }}</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-testimonial-carusel">
                {% for comment in CommentContent %}
                    <div class="single-testimonial item d-flex flex-row">
                        <div class="thumb">
                            <img class="img-fluid" src="{{ comment.image.url }}" alt="{{ comment.image_alt }}">
                        </div>
                        <div class="desc">
                            <p>{{ comment.description }}</p>
                            <h4 mt-30>{{ comment.name }}</h4>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!-- End testimonial Area -->
{% endblock MainContent %}

{% block CustomJs %}
<script>
    $(document).ready(function(){
        // Hide more details buttons from initial page load
        $(".more-detail").fadeOut(0);

        // For each grid row
        $(".grid-row").each(function(){
            var is_limited = false;
            var itemCount = parseInt($(this).attr("col-count")) * 2;
            $(this).find(".grid-item").each(function(index){
                if(index >= itemCount){
                    is_limited = true;
                    $(this).attr("class", $(this).attr("class") + " fade-in");
                }
            });
            // Show more details button if number of item is limited
            if(is_limited){
                $(this).find(".more-detail").fadeIn(0);
            }
        });

        // Animation effects
        $(".fade-in").fadeOut(0);
        $(".more-detail").click(function(){
            $(".fade-in").fadeIn(2000);
            $(this).hide();
        });
    });
</script>
{% endblock CustomJs %}

movento_root/movento_web_app/templates/success.html
{% extends "base.html" %}
{% load static %}
{% block Title %}
Cảm ơn !
{% endblock Title %}

{% block MainContent %}
<link rel="stylesheet" href="{% static 'css/custom_css/homepage.css' %}">

<style>
    {% with CoverContent.contentimages_set.all|first as firstItem %}
        .banner-area {
            background: url({{ firstItem.image.url }}) center;
            background-size: cover;
        }
    {% endwith %}
</style>

<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Gửi yêu cầu thành công
                </h1>
                <p class="text-white link-nav"><a href="{% url 'home' %}">Trang chủ </a>  <span class="lnr lnr-arrow-right"></span>  <a href="">Gửi yêu cầu thành công</a></p>
            </div>
        </div>
    </div>
</section>

<div class="container pt-50 pb-50" style="text-align:center">
    <h1>Cảm ơn bạn !</h1>
    <p>Bạn Đã Đăng Ký Thành Công Chúng Tôi Sẽ Liên Hệ Với Bạn Trong Thời Gian Nhanh Nhất</p>
</div>
{% endblock MainContent %}

{% block CustomJs %}
<script>
    $(".callto-action-area").hide();
    $(".brands-area").hide();
    $("footer").hide();
</script>
{% endblock CustomJs %}